package model;

import java.util.UUID;

/**
 * Represents a client-side message. It is randomly generated by {@link util.MessageGenerator} for testing purpose.
 * Each message is assigned a unique identifier upon creation.
 */

public class ClientMessage {
  private String userId;
  private String username;
  private String message;
  private String timestamp;
  private MessageType messageType;
  private String roomId;
  private final String messageId;

  public ClientMessage() {
    this.messageId = UUID.randomUUID().toString();
  }

  public ClientMessage(String userId, String username, String message, String timestamp, MessageType messageType,
      String roomId) {
//    Generate a unique identifier for this message
    this.messageId = UUID.randomUUID().toString();
    this.userId = userId;
    this.username = username;
    this.message = message;
    this.timestamp = timestamp;
    this.messageType = messageType;
    this.roomId = roomId;
  }

  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public String getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(String timestamp) {
    this.timestamp = timestamp;
  }

  public MessageType getMessageType () {
    return messageType;
  }

  public void setMessageType(MessageType messageType) {
    this.messageType = messageType;
  }

  public String getRoomId() {
    return roomId;
  }

  public void setRoomId(String roomId) {
    this.roomId = roomId;
  }

  //  We do not have setter for MessageId since it is generated by the system
  public String getMessageId() {
    return messageId;
  }
}
